"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pMtS9AWrlQk
 */

import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Dropzone } from "../ui/dropzone";
import { useState, useEffect } from "react";
import { DataTableDemo, NetworkPackets } from "./Table";
export function Component() {
  const [uploadedFiles, setUploadedFiles] = useState<string[]>([]);
  const [data, setData] = useState<NetworkPackets[]>([]);
  const [loading, setLoading] = useState<boolean>(false);

  // Function to handle the change in uploaded files
  const handleFileChange: React.Dispatch<React.SetStateAction<string[]>> = (
    newState: React.SetStateAction<string[]>
  ) => {
    setUploadedFiles(newState);
  };

  // remove this useEffect hook if you don't need to do anything with the uploaded files
  useEffect(() => {
    console.log(uploadedFiles);
  }, [uploadedFiles]);

  //function to save the file on the server
  const handleAnalyse = async () => {
    //get the last file uploaded
    const filePath = uploadedFiles[uploadedFiles.length - 1];
    const file = await fetch(filePath).then((res) => res.blob());
    const formData = new FormData();
    formData.append("file", file);

    setLoading(true);

    await fetch("http://127.0.0.1:5000/upload", {
      method: "POST",
      body: formData,
    })
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
        setData(data);
        setLoading(false);
      });
  };

  return (
    <section className="w-full  py-4">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col  items-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
              AI based Network Intrusion Detection System
            </h1>
            <p className="mx-auto max-w-[700px] text-gray-700 md:text-xl dark:text-gray-400">
              TNN Based Intrusion detection system in MQTT protocol
            </p>
            <p className="mx-auto max-w-[700px] text-gray-700 md:text-xl dark:text-gray-400">
              Implemented by
            </p>
            <div>
              {/* team */}
              <div className="flex items-center justify-center space-x-4">
                <div className="flex items-center space-x-2">
                  <img
                    src="https://avatars.githubusercontent.com/u/55926959?s=400&u=4f6f9e3b2e1e5f1c8f3c9a9d4
                  5e0e2f9a3f4b8a6&v=4"
                    alt="avatar"
                    className="w-12 h-12 rounded-full"
                  />
                  <div>
                    <h2 className="text-lg font-semibold">
                      Shubham Subodh Rasal
                    </h2>
                    <p>211IT066</p>
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  <img
                    src="https://avatars.githubusercontent.com/u/55926959?s=400&u=4f6f9e3b2e1e5f1c8f3c9a9d4
                  5e0e2f9a3f4b8a6&v=4"
                    alt="avatar"
                    className="w-12 h-12 rounded-full"
                  />
                  <div>
                    <h2 className="text-lg font-semibold">Mohd. Dilshad</h2>
                    <p>211IT042</p>
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  <img
                    src="https://avatars.githubusercontent.com/u/55926959?s=400&u=4f6f9e3b2e1e5f1c8f3c9a9d4
                  5e0e2f9a3f4b8a6&v=4"
                    alt="avatar"
                    className="w-12 h-12 rounded-full"
                  />
                  <div>
                    <h2 className="text-lg font-semibold">Subhojit Karmakar</h2>
                    <p>211IT071</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full max-w-sm space-y-2">
            <div className="grid grid-cols-[1fr_min-content] gap-2 justify-center">
              <Dropzone
                onChange={handleFileChange} // Pass the handler function
                fileExtension="csv" // Set the expected file extension
              />
            </div>
            <Button onClick={handleAnalyse} size="lg">
              {loading ? (
                <div className="flex items-center justify-center space-x-2">
                  <p>Analysing</p>

                  <div role="status">
                    <svg
                      aria-hidden="true"
                      className="w-8 h-8 text-gray-200 animate-spin dark:text-gray-600 fill-slate-600"
                      viewBox="0 0 100 101"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
                        fill="currentColor"
                      />
                      <path
                        d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
                        fill="currentFill"
                      />
                    </svg>
                    <span className="sr-only">Analysing...</span>
                  </div>
                </div>
              ) : (
                "Analyse"
              )}
            </Button>
          </div>
        </div>
      </div>
      <DataTableDemo data={data} />
    </section>
  );
}
