"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pMtS9AWrlQk
 */

import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Dropzone } from "../ui/dropzone";
import { useState, useEffect } from "react";
import { DataTableDemo, NetworkPackets } from "./Table";
export function Component() {
  const [uploadedFiles, setUploadedFiles] = useState<string[]>([]);
  const [data, setData] = useState<NetworkPackets[]>([]);

  // Function to handle the change in uploaded files
  const handleFileChange: React.Dispatch<React.SetStateAction<string[]>> = (
    newState: React.SetStateAction<string[]>
  ) => {
    setUploadedFiles(newState);
  };

  // remove this useEffect hook if you don't need to do anything with the uploaded files
  useEffect(() => {
    console.log(uploadedFiles);
  }, [uploadedFiles]);

  //function to save the file on the server
  const handleAnalyse = async () => {
    // "blob:http://localhost:3000/6546b0ac-6f4f-44af-8b6a-f09c7805b5b2"
    const filePath = uploadedFiles[0];
    const file = await fetch(filePath).then((res) => res.blob());
    const formData = new FormData();
    formData.append("file", file);
    await fetch("http://localhost:5000/upload", {
      method: "POST",
      body: formData,
    })
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
        setData(data);
      });
  };

  return (
    <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
              AI based Network Intrusion Detection System
            </h1>
            <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              TNN Based Intrusion detection system in mqtt protocol
            </p>
            <div>
              {/* team */}
              <div className="flex items-center justify-center space-x-4">
                <div className="flex items-center space-x-2">
                  <img
                    src="https://avatars.githubusercontent.com/u/55926959?s=400&u=4f6f9e3b2e1e5f1c8f3c9a9d4
                  5e0e2f9a3f4b8a6&v=4"
                    alt="avatar"
                    className="w-12 h-12 rounded-full"
                  />
                  <div>
                    <h2 className="text-lg font-semibold">Shubham Subodh Rasal</h2>
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  <img
                    src="https://avatars.githubusercontent.com/u/55926959?s=400&u=4f6f9e3b2e1e5f1c8f3c9a9d4
                  5e0e2f9a3f4b8a6&v=4"
                    alt="avatar"
                    className="w-12 h-12 rounded-full"
                  />
                  <div>
                    <h2 className="text-lg font-semibold">Mohd. Dilshad</h2>
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  <img
                    src="https://avatars.githubusercontent.com/u/55926959?s=400&u=4f6f9e3b2e1e5f1c8f3c9a9d4
                  5e0e2f9a3f4b8a6&v=4"
                    alt="avatar"
                    className="w-12 h-12 rounded-full"
                  />
                  <div>
                    <h2 className="text-lg font-semibold">Subhojit Karmakar</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full max-w-sm space-y-2">
            <div className="grid grid-cols-[1fr_min-content] gap-2 justify-center">
              <Dropzone
                onChange={handleFileChange} // Pass the handler function
                fileExtension="csv" // Set the expected file extension
              />
            </div>
            <Button onClick={handleAnalyse} size="lg">
              Analyse
            </Button>

            
          </div>
        </div>
      </div>
      <DataTableDemo data={data} />
    </section>
  );
}
